### ISSUE TITLE
Failing to complete downloads

### ISSUE THREAD

**Issue by SDRoffey** [ribbons/RadioDownloader#256] opened 2023-05-12 08:44 UTC
Hi,

Recently I've had an increasing number of downloads failing to complete. The progress bar will get about 90% of the way across, the info panel on the left will 'blink', and the download fails with 'Error' in the 'Status' column. Sometimes they work after 2-3 attempts, but often not. These are the URLs of some consistent failures.

https://feeds.megaphone.fm/cautionarytales
https://www.spreaker.com/show/4206464/episodes/feed
https://omny.fm/shows/trackside/playlists/podcast-1.rss
https://feeds.megaphone.fm/ESP5431173087

If I go to the webpage for any of these podcasts the programs download without issues.

Can you investigate?

Many thanks,

Simon

**Comment by ribbons** [comment] 2023-05-13 08:53
I just successfully downloaded the latest episode from that first podcast feed you gave with an instance of Radio Downloader here.  What details are shown about the error in the info panel if you select one of the errored downloads?

**Comment by SDRoffey** [comment] 2023-05-15 08:45
Hi,

Thanks for getting back to me.

When a download fails at the bottom of the LH panel it says:

_Error: Network problem

Received an unexpected EOF or 0 bytes from the transport stream_.

Hope this helps.

Simon

**Comment by ribbons** [comment] 2023-05-16 14:37
Sounds like the download is being interrupted somehow based on that error message and that it works okay at this end...  That error is being passed back to Radio Downloader from the .NET framework so I'm not really sure if there is much that can be done from an application perspective?

**Comment by SDRoffey** [comment] 2023-05-23 16:06
Hi,

This does seem to be a network issue. I normally use a Mifi on the Three network for my internet access. When I use a hotspot on my phone (on Virgin-O2) they seem to download correctly.

Strangely this issue only happens downloading with Radio Downloader. If I download the same programs from their RSS feed (I use FireFox with the Livemarks add-on), they download irrespective of the network.

Regards,

Simon

**Comment by ribbons** [comment] 2023-05-24 19:25
Thanks for the update - definitely more speculation on my part than insight but I wonder if the difference in behaviour might be caused by a difference in how the Firefox and .NET low level networking code handles particular scenarios?  I'll close this for now but feel free to reopen in future if you make a further discovery that sheds light on the mystery.

**Closed by ribbons** 2023-05-24 19:25 UTC
Labels: bug, needinfo
