### ISSUE TITLE
Podcast episodes with URL encoded enclosure URLs are treated as invalid

### ISSUE THREAD

**Issue by cjpcjpindre** [ribbons/RadioDownloader#226] opened 2018-11-15 00:29 UTC
Hi,

Have added a feed to RD:
https://anchor.fm/s/7368c04/podcast/rss

RD was quite happy to add it, so recognised it as an rss feed. But it has not downloaded anything from the feed.  Current Episode list empty in RD. Browsing the rss feed shows Four Episodes. 

Not sure if this is bug in RD, or dodgy encoding on the rss feed.

**Comment by ribbons** [comment] 2018-11-16 16:33
Thanks for your bug report - I can reproduce this problem.

The reason it isn't showing any episodes is that the episode audio file (enclosure) URLs are checked with `Uri.IsWellFormedUriString` to make sure they are valid and this is returning `false` for all of the URLs in the feed, causing them to be skipped over.

However what I'm not quite seeing at the moment is why `IsWellFormedUriString` is returning false - as an example, this is one of the URLs in the feed which doesn't look obviously invalid but fails the test.

```
https://anchor.fm/s/7368c04/podcast/play/1722642/https%3A%2F%2Fd3ctxlq1ktw2nl.cloudfront.net%2Fstaging%2F2018-10-13%2FJohn-Kearns-782f1f393cd0f.m4a
```

**Comment by ribbons** [comment] 2018-11-18 20:31
Right, I managed to get to the bottom of this in the end :smile:.

If you'd like to download and install the build of Radio Downloader from [here](https://ci.appveyor.com/api/buildjobs/kfg0tbd0q1dppr3v/artifacts/installer%2FRadio_Downloader-win64.msi) it should then list the episodes of that podcast feed correctly.  Let me know how you get on...

**Comment by cjpcjpindre** [comment] 2018-11-19 00:01
Hi,

Thanks, (as ever) for the quick response. 

I've installed the new build. Partial success. RD is listing the episodes:
![screenshot 101](https://user-images.githubusercontent.com/45052954/48679919-b4246400-eb8d-11e8-9ada-07b243014b20.jpg)

However, there is the following error when trying to download the latest episode after subscribing:
"Error: Not available
This episode appears to be no longer available.  You can either try again later, or cancel the download to remove it from the list and clear the error."

**Comment by ribbons** [comment] 2018-11-19 20:09
Turns out I should have tested actually downloading the episodes too :smile:. I'll close this bug and open a new one for the downloading issue as from a quick look it is being caused by a related but slightly different issue.

**Closed** 2018-11-19 20:10 UTC
Labels: bug
