### ISSUE TITLE
Failure to download specific feed

### ISSUE THREAD

**Issue by DonGrunbaum** [ribbons/RadioDownloader#252] opened 2022-04-14 13:17 UTC
Recent episodes from F1:Beyond the Grid are failing to download.
![image](https://user-images.githubusercontent.com/28298234/163397857-7e530500-b25e-41f8-ada1-2ab52cdbd859.png)

**Comment by ribbons** [comment] 2022-04-14 15:19
Thanks for your report - what does it say about the download error if you scroll to the bottom of the text in the sidebar?

**Comment by DonGrunbaum** [comment] 2022-04-14 19:10
It saysError: Network problem The remote name could not be resolved: 'pdst.fm'I've successfully downloaded earlier podcasts from this feed and all other feeds are working fine.Thanks for the quick response. Don Grunbaum On 14 Apr 2022 16:19, Matt Robinson ***@***.***> wrote:
Thanks for your report - what does it say about the download error if you scroll to the bottom of the text in the sidebar?

**Comment by ribbons** [comment] 2022-04-14 19:39
Interesting, I wonder if their podcast host is having some kind of issues at the moment, I just tried downloading the episode shown in your screenshot and I get the following error under Windows 10:
![error](https://user-images.githubusercontent.com/961548/163463302-f711b163-a9f5-421d-9ba2-9d4ead2b4faf.png)

**Comment by DonGrunbaum** [comment] 2022-04-14 19:59
I'm on Windows 10 as well. On one of the episodes (11/04/2022) I get the same error as you, but three others give the error that I sent you. I can listen directly through Acast, so it's probably a problem with their RSS feed.As I said previously, earlier episodes downloaded fine.DonOn 14 Apr 2022 20:40, Matt Robinson ***@***.***> wrote:
Interesting, I wonder if their podcast host is having some kind of issues at the moment, I just tried downloading the episode shown in your screenshot and I get the following error under Windows 10:

**Comment by ribbons** [comment] 2022-04-15 19:46
Okay, thanks for the update - yes, that does sound plausible.  In that case I'll close this for now but feel free to reopen it if you discover it is caused by an issue with Radio Downloader.

**Closed by ribbons** 2022-04-15 19:46 UTC
Labels: bug, invalid
